activate_boost:
  description: Activate the boost mode
  fields:
    device:
      description: Serial number of the device to target. Can be omitted if you're only using one device.
      example: 2001000912110212

set_power:
  description: Set the amount of power to be used by the device
  fields:
    device:
      description: Serial number of the device to target. Can be omitted if you're only using one device.
      example: 2001000912110212

    power:
      description: Excess power in watts
      example: 500

    override:
      description: Whether to set the override power. Defaults to false.
      example: true

    mode:
      description: >-
        Override mode, only applicable if `override` is `true`.
        If not specified, the previous override mode is kept.

        Valid values are:

          - override: Use the value unless it is 0 (Initial setting).
          - replace: Ignore the excess power entirely and only use this value.
          - minimum: Use this value as the minimum, using the excess power if it's bigger.

      example: minimum
